version: "3.7"

services:
### PHP Container #########################################
  decoratorphp:
    container_name: decorator-php
    hostname: decorator-php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html/app
    volumes:
      - ./:/var/www/html/app
    depends_on:
      - decoratordb
      - decoratorredis


  ### NGINX Container #########################################
  nginx:
    container_name: decorator-nginx
    image: nginx:1.17
    restart: unless-stopped
    depends_on:
      - decoratorphp
    ports:
      - 5000:80
    volumes:
      - ./:/var/www/html/app
      - ./docker/virtualhost.conf:/etc/nginx/conf.d/default.conf

### POSTGRESS Container #########################################
  decoratordb:
    container_name: decorator-db
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: decorator
      POSTGRES_USER: decorator-user
      POSTGRES_PASSWORD: secret
      PGPASSWORD: secret
    ports:
      - "54321:5432"

### Redis Container #########################################
  decoratorredis:
    container_name: decorator-redis
    image: redis:5.0
    expose:
      - 6379
    volumes:
      - redis-data:/data

volumes:
  redis-data: